language: ruby
bundler_args: --quiet
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2
  - 2.1.5
  - 2.2.0
  - ruby-head
script: "bundle exec rake"
gemfile:
  - Gemfile
notifications:
  recipients:
    - lourens@methodmissing.com
branches:
  only:
    - master
